Repository georgia-tech-db/evadb, pull requests merged in 2023-06, with the labels that each got.

#801 feat / doc: example app that summarizes any youtube video with eva api
  .gitignore
  docs/_toc.yml
  docs/source/reference/faq.rst
  eva/udfs/chatgpt.py
  examples/privategpt/README.md
  examples/privategpt/example.env
  examples/privategpt/ingest.py
  examples/privategpt/privateGPT.py
  examples/privategpt/requirements.txt
  examples/youtube_qa/README.md
  examples/youtube_qa/youtube_qa.py
  privategpt/README.md
  privategpt/example.env
  privategpt/ingest.py
  privategpt/privateGPT.py
  privategpt/requirements.txt
  script/formatting/spelling.txt
Labels: Documentation 📗

#803 feat: saliency maps
  data/saliency/test1.jpeg
  data/saliency/test2.jpeg
  eva/udfs/saliency_feature_extractor.py
  test/integration_tests/test_saliency.py
Labels: Work In Progress 🚧

#818 fix: update youtube qa app with new api updates
  examples/youtube_qa/youtube_qa.py
Labels: Minor 💅

#800 test: api testing -> similarity between text and relevance keyword
  data/documents/state_of_the_union.pdf
  eva/binder/statement_binder.py
  eva/udfs/sentence_transformer_feature_extractor.py
  eva/udfs/udf_bootstrap_queries.py
  script/formatting/formatter.py
  setup.py
  test/integration_tests/test_load_executor.py
  test/interfaces/relational/test_relational_api.py
  tutorials/12-query-pdf.ipynb
  tutorials/13-privategpt.ipynb
Labels: Work In Progress 🚧

#886 doc: improve youtube qa app doc
  apps/youtube_qa/README.md
Labels: Documentation 📗
