Repository georgia-tech-db/evadb, pull requests merged in 2023-08, with the labels that each got.

#953 docs: Fix User Reference and Dev Guide
  docs/_static/custom.css
  docs/_static/icons/github-no-fill.png
  docs/_static/js/top-navigation.js
  docs/_toc.yml
  docs/source/contribute/debugging.rst
  docs/source/contribute/index.rst
  docs/source/contribute/new-command.rst
  docs/source/reference/udfs/index.rst
  docs/source/reference/udfs/model-train.rst
  docs/source/usecases/02-object-detection.md
Labels: Documentation 📗

#946 Support `SELECT Func(*) FROM Table`.
  docs/source/reference/udfs/model-train.rst
  evadb/binder/statement_binder.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_functions.py
  test/binder/test_statement_binder.py
  test/integration_tests/test_model_train.py
  test/parser/test_parser.py
Labels: Feature Request ✨, High Effort 🏋

#966 Developer guide for new structure data source integration
  docs/_toc.yml
  docs/source/contribute/extend.rst
  docs/source/contribute/new-command.rst
  docs/source/contribute/new-data-source.rst
  evadb/third_party/databases/types.py
Labels: Documentation 📗

#975 Simplify the ludwig dependency
  .circleci/config.yml
  setup.py
Labels: Crash 💥

#997 fix: improve error msg
  evadb/executor/use_executor.py
  test/integration_tests/short/test_use_executor.py
Labels: Bug 🐞

#1006 fix: update more verbose message for creating database
  evadb/executor/create_database_executor.py
  test/integration_tests/short/test_create_database_executor.py
  test/third_party_tests/test_native_executor.py
Labels: Bug 🐞

#1007 fix: create Table fails when projecting column from native table
  docs/source/usecases/food-review.rst
  evadb/binder/binder_utils.py
  evadb/binder/statement_binder_context.py
  evadb/catalog/catalog_type.py
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/postgres/postgres_handler.py
  evadb/third_party/databases/types.py
  setup.py
  test/third_party_tests/test_native_executor.py
Labels: Bug 🐞

#1008 fix: CREATE TABLE persists entry in the catalog even if the query fails
  evadb/executor/create_executor.py
Labels: Bug 🐞

#1014 Extend the circle ci link check to include README.md
  .circleci/config.yml
  README.md
  docs/_toc.yml
  docs/conf.py
  script/test/link_check_config.json
  script/test/test.sh
Labels: Documentation 📗

#1016 Revamp getting started.
  docs/_toc.yml
  docs/source/dev-guide/contribute.rst
  docs/source/dev-guide/extend/new-data-source.rst
  docs/source/overview/getting-started/data-source.rst
  docs/source/overview/getting-started/install-guide.rst
  docs/source/reference/api.rst
  docs/source/reference/databases/index.rst
  docs/source/reference/databases/postgres.rst
  docs/source/reference/evaql/create.rst
  docs/source/reference/evaql/load.rst
  docs/source/reference/evaql/select.rst
  docs/source/reference/evaql/use.rst
Labels: Documentation 📗

#965 msyql integration added
  evadb/catalog/catalog_utils.py
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/mysql/__init__.py
  evadb/third_party/databases/mysql/mysql_handler.py
  evadb/third_party/databases/mysql/requirements.txt
  test/third_party_tests/test_native_executor.py
  test/unit_tests/storage/test_mysql_native_storage_engine.py
  test/unit_tests/storage/test_postgres_native_storage_engine.py
Labels: Integrations 🧩
