Repository georgia-tech-db/evadb, pull requests merged in 2023-09, with the labels that each got.

#1025 Add mysql as an available data source into documentation
  docs/_toc.yml
  docs/source/dev-guide/contribute/setup-dev.rst
  docs/source/dev-guide/extend/new-data-source.rst
  docs/source/overview/connect-to-database.rst
  docs/source/overview/getting-started.rst
  docs/source/overview/getting-started/installation-options.rst
  docs/source/reference/databases/mysql.rst
  docs/source/reference/evaql/create.rst
Labels: Documentation 📗

#1029 Fix the link in new-data-source.rst
  docs/source/dev-guide/extend/new-data-source.rst
Labels: Documentation 📗

#969 Forecasting in EVA
  .circleci/config.yml
  data/forecasting/air-passengers.csv
  docs/_toc.yml
  docs/source/reference/ai/custom.rst
  docs/source/reference/udfs/model-forecasting.rst
  docs/source/usecases/question-answering.rst
  evadb/binder/statement_binder.py
  evadb/executor/create_udf_executor.py
  evadb/udfs/forecast.py
  evadb/utils/generic_utils.py
  setup.py
  test/integration_tests/long/test_model_forecasting.py
  test/markers.py
Labels: High Priority ⚡️

#1026 Removing quotes from udf_metadata_key
  README.md
  benchmark/text_summarization/text_summarization_with_evadb.py
  docs/_toc.yml
  docs/source/benchmarks/text_summarization.rst
  docs/source/overview/concepts.rst
  docs/source/reference/ai/hf.rst
  docs/source/reference/ai/model-forecasting.rst
  docs/source/reference/ai/model-train.rst
  docs/source/reference/ai/openai.rst
  docs/source/reference/ai/yolo.rst
  docs/source/reference/evaql/create.rst
  docs/source/usecases/object-detection.rst
  docs/source/usecases/question-answering.rst
  docs/source/usecases/text-summarization.rst
  evadb/functions/function_bootstrap_queries.py
  evadb/parser/create_function_statement.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_functions.py
  evadb/parser/utils.py
  test/benchmark_tests/test_benchmark_pytorch.py
  test/integration_tests/long/interfaces/relational/test_relational_api.py
  test/integration_tests/long/test_error_handling_with_ray.py
  test/integration_tests/long/test_function_executor.py
  test/integration_tests/long/test_huggingface_functions.py
  test/integration_tests/long/test_model_forecasting.py
  test/integration_tests/long/test_model_train.py
  test/integration_tests/long/test_reuse.py
  test/unit_tests/parser/test_parser.py
Labels: Feature Request ✨

#1043 Hot fix forecasting
  evadb/binder/statement_binder.py
  evadb/functions/forecast.py
  test/integration_tests/long/test_model_forecasting.py
Labels: Bug 🐞

#1080 `pandas.DataFrame.fillna` is deprecated
  evadb/models/storage/batch.py
Labels: Minor 💅

#1073 fix: create index from single document
  evadb/catalog/sql_config.py
  evadb/executor/create_index_executor.py
  evadb/executor/vector_index_scan_executor.py
  evadb/readers/decord_reader.py
  evadb/readers/document/document_reader.py
  evadb/readers/pdf_reader.py
  evadb/storage/document_storage_engine.py
  evadb/storage/image_storage_engine.py
  evadb/storage/pdf_storage_engine.py
  evadb/storage/sqlite_storage_engine.py
  evadb/storage/video_storage_engine.py
  test/integration_tests/long/test_single_document_similarity.py
  test/unit_tests/readers/test_decord_reader.py
  test/unit_tests/storage/test_sqlite_storage_engine.py
  test/util.py
Labels: Bug 🐞

#1084 Fix column name related issue for Forecast functions
  data/forecasting/home_sales.csv
  evadb/executor/create_function_executor.py
  evadb/functions/forecast.py
  test/integration_tests/long/test_model_forecasting.py
Labels: Bug 🐞

#1086 Update parameters documentation for forecast
  docs/source/reference/ai/model-forecasting.rst
Labels: Documentation 📗

#1088 fix: df merging issues when multiple predicates
  evadb/expression/logical_expression.py
Labels: Bug 🐞

#1082 feat: create index if exists
  docs/source/reference/evaql/create.rst
  evadb/executor/create_index_executor.py
  evadb/optimizer/operators.py
  evadb/optimizer/rules/rules.py
  evadb/optimizer/statement_to_opr_converter.py
  evadb/parser/create_index_statement.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_create_statements.py
  evadb/plan_nodes/create_index_plan.py
  test/integration_tests/long/test_create_index_executor.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
  test/unit_tests/parser/test_parser.py
Labels: Feature Request ✨

#1092 feat: Drop database
  docs/source/reference/evaql/drop.rst
  evadb/catalog/catalog_manager.py
  evadb/executor/drop_object_executor.py
  evadb/parser/lark_visitor/_drop_statement.py
  evadb/parser/types.py
  evadb/parser/utils.py
  test/integration_tests/short/test_drop_executor.py
Labels: Feature Request ✨

#1091 fix: evadb is now consistent with lowercase
  evadb/binder/binder_utils.py
  evadb/binder/statement_binder_context.py
  evadb/storage/native_storage_engine.py
  evadb/third_party/databases/sqlite/sqlite_handler.py
  test/third_party_tests/test_native_executor.py
Labels: Bug 🐞, Crash 💥

#1101 Fix forecasting integration test
  test/integration_tests/long/test_model_forecasting.py
Labels: Bug 🐞

#1027 Adding support for MariaDb as backend for EvaDB
  docs/_toc.yml
  docs/source/reference/databases/mariadb.rst
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/mariadb/__init__.py
  evadb/third_party/databases/mariadb/mariadb_handler.py
  evadb/third_party/databases/mariadb/requirements.txt
  test/third_party_tests/test_native_executor.py
  test/unit_tests/storage/test_mariadb_native_storage_engine.py
Labels: Integrations 🧩

#1087 Support `SELECT expr;` which does not require `FROM table`
  docs/source/reference/ai/model-forecasting.rst
  docs/source/reference/evaql/select.rst
  evadb/binder/statement_binder.py
  evadb/executor/project_executor.py
  evadb/optimizer/rules/rules.py
  evadb/optimizer/rules/rules_base.py
  evadb/optimizer/rules/rules_manager.py
  evadb/optimizer/statement_to_opr_converter.py
  evadb/parser/evadb.lark
  test/integration_tests/long/test_model_forecasting.py
  test/integration_tests/short/test_select_executor.py
  test/unit_tests/binder/test_statement_binder.py
  test/unit_tests/executor/test_project_executor.py
  test/unit_tests/expression/test_constant.py
  test/unit_tests/optimizer/rules/test_rules.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
  test/unit_tests/parser/test_parser.py
  test/unit_tests/parser/test_parser_statements.py
Labels: Feature Request ✨

#1108 Set the right output column type for forecast functions
  evadb/binder/statement_binder.py
  evadb/executor/create_function_executor.py
  evadb/functions/forecast.py
  test/integration_tests/long/test_model_forecasting.py
  test/unit_tests/binder/test_statement_binder.py
  test/unit_tests/utils/test_generic_utils.py
Labels: Bug 🐞

#1122 fix: flaky ci unit tests
  test/unit_tests/server/test_interpreter.py
Labels: Bug 🐞

#1125 feat: create table in integration table from evadb select query
  evadb/executor/create_executor.py
  evadb/executor/use_executor.py
  evadb/storage/native_storage_engine.py
  evadb/third_party/databases/sqlite/sqlite_handler.py
  test/third_party_tests/test_native_executor.py
Labels: Feature Request ✨, High Effort 🏋

#1124 fix: third-party test
  .circleci/config.yml
  evadb/storage/native_storage_engine.py
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/mariadb/mariadb_handler.py
  evadb/third_party/databases/mysql/mysql_handler.py
  evadb/third_party/databases/postgres/postgres_handler.py
  script/test/test.sh
Labels: Bug 🐞

#1030 Add model inference documentation
  docs/_toc.yml
  docs/source/overview/connect-to-database.rst
  docs/source/overview/model-inference.rst
  docs/source/reference/ai/custom.rst
  docs/source/reference/ai/index.rst
  docs/source/reference/optimizations.rst
Labels: Documentation 📗

#1136 feat: support order by using the projection columns
  evadb/binder/binder_utils.py
  evadb/binder/statement_binder.py
  evadb/optimizer/statement_to_opr_converter.py
  test/integration_tests/long/test_model_forecasting.py
  test/integration_tests/long/test_pytorch.py
Labels: Feature Request ✨

#1154 feat: add github actions to sync and release wheel
  .github/workflows/release.yml
  .github/workflows/sync.yml
  docs/source/dev-guide/release/pypi-account.rst
  docs/source/dev-guide/release/release-steps-old.rst
  docs/source/dev-guide/release/release-steps.rst
Labels: Feature Request ✨

#1146 `CREATE OR REPLACE FUNCTION`
  docs/source/overview/model-inference.rst
  docs/source/reference/ai/model-train.rst
  docs/source/reference/evaql/create.rst
  evadb/executor/create_function_executor.py
  evadb/optimizer/operators.py
  evadb/optimizer/rules/rules.py
  evadb/optimizer/statement_to_opr_converter.py
  evadb/parser/create_function_statement.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_functions.py
  evadb/plan_nodes/create_function_plan.py
  test/integration_tests/long/test_function_executor.py
  test/unit_tests/executor/test_create_udf_executor.py
  test/unit_tests/executor/test_plan_executor.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
  test/unit_tests/parser/test_parser.py
  test/unit_tests/plan_nodes/test_plan.py
Labels: Feature Request ✨

#1158 Adding Algolia search to Eva-DB Docs
  docs/_static/algolia.css
  docs/_static/js/algolia.js
  docs/conf.py
Labels: Documentation 📗

#1155 feat: add support for enabling ORDER BY on non projected columns
  evadb/binder/binder_utils.py
  evadb/binder/statement_binder.py
  evadb/optimizer/statement_to_opr_converter.py
  test/integration_tests/short/test_select_executor.py
Labels: Feature Request ✨, High Effort 🏋

#1164 Fix model train with Ludwig on Colab
  evadb/functions/ludwig.py
  evadb/models/storage/batch.py
  evadb/utils/generic_utils.py
Labels: Bug 🐞

#1135 Pinecone vector store
  docs/source/dev-guide/contribute/testing.rst
  evadb/catalog/catalog_type.py
  evadb/evadb.yml
  evadb/executor/executor_utils.py
  evadb/interfaces/relational/db.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_create_statements.py
  evadb/third_party/vector_stores/pinecone.py
  evadb/third_party/vector_stores/utils.py
  evadb/utils/generic_utils.py
  script/formatting/spelling.txt
  setup.py
  test/integration_tests/long/test_similarity.py
Labels: Integrations 🧩

#1153 feat: integrate with pgvector
  evadb/binder/create_index_statement_binder.py
  evadb/binder/statement_binder.py
  evadb/catalog/catalog_type.py
  evadb/executor/create_index_executor.py
  evadb/executor/vector_index_scan_executor.py
  evadb/optimizer/operators.py
  evadb/optimizer/rules/rules.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/__init__.py
  evadb/parser/lark_visitor/_create_statements.py
  evadb/plan_nodes/abstract_plan.py
  evadb/plan_nodes/vector_index_scan_plan.py
  evadb/third_party/databases/postgres/postgres_handler.py
  test/third_party_tests/test_native_similarity_index.py
Labels: Feature Request ✨, High Effort 🏋

#1185 Add support for function calls without input arguments: `FUNC()`
  evadb/functions/function_bootstrap_queries.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_functions.py
  test/integration_tests/short/test_select_executor.py
  test/util.py
Labels: Feature Request ✨, User Experience

#1167 Model training Colab Notebook
  tutorials/17-home-rental-prediction.ipynb
Labels: Documentation 📗, AI Engines

#1196 bug: fix links in model training notebook
  tutorials/17-home-rental-prediction.ipynb
Labels: Bug 🐞

#1162 Adding support for Sklearn linear regression in EvaDB
  evadb/binder/statement_binder.py
  evadb/executor/create_function_executor.py
  evadb/functions/sklearn.py
  evadb/utils/generic_utils.py
  test/integration_tests/long/test_model_train.py
Labels: Integrations 🧩, AI Engines

#1198 Chroma vector store
  .circleci/config.yml
  evadb/catalog/catalog_type.py
  evadb/executor/executor_utils.py
  evadb/interfaces/relational/db.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_create_statements.py
  evadb/third_party/vector_stores/chromadb.py
  evadb/third_party/vector_stores/utils.py
  evadb/utils/generic_utils.py
  script/formatting/spelling.txt
  setup.py
  test/integration_tests/long/test_similarity.py
  test/markers.py
Labels: Integrations 🧩, Data Sources

#1180 Adding SET statement for configuration management
  evadb/executor/plan_executor.py
  evadb/executor/set_executor.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/__init__.py
  evadb/parser/lark_visitor/_set_statement.py
  evadb/parser/set_statement.py
  evadb/parser/types.py
  evadb/parser/utils.py
  test/integration_tests/short/test_set_executor.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
  test/unit_tests/parser/test_parser.py
Labels: User Experience

#1204 feat: print error msg if creating built-in functions failed
  evadb/executor/create_function_executor.py
  evadb/functions/function_bootstrap_queries.py
Labels: User Experience

#1208 fix: if create table fails, we were not cleaning the entry in catalog
  evadb/executor/create_executor.py
  test/integration_tests/long/test_create_table_executor.py
Labels: Bug 🐞

#1203 fix: chatgpt exact cache
  evadb/functions/chatgpt.py
  evadb/functions/function_bootstrap_queries.py
  evadb/optimizer/optimizer_utils.py
  test/integration_tests/long/test_reuse.py
  test/util.py
Labels: Optimizations

#1211 fix: evadb_client fails on launch
  evadb/server/interpreter.py
Labels: Bug 🐞, User Experience

#1212 fix: 1199 enhance similarity search test to make index is used
  evadb/catalog/services/index_catalog_service.py
  evadb/executor/executor_utils.py
  evadb/third_party/vector_stores/pinecone.py
  test/integration_tests/long/test_similarity.py
Labels: Bug 🐞, User Experience

#1201 Improve Documentation For Model Training
  docs/_toc.yml
  docs/source/overview/model-inference.rst
  docs/source/reference/ai/model-forecasting.rst
  docs/source/reference/ai/model-train-ludwig.rst
  docs/source/reference/ai/model-train-sklearn.rst
  docs/source/reference/ai/model-train.rst
  docs/source/reference/evaql/create.rst
  docs/source/usecases/homerental-predict.rst
  docs/source/usecases/homesale-forecast.rst
  script/test/test.sh
Labels: Documentation 📗, AI Engines

#1209 feat: add testmon in pytest
  .circleci/config.yml
  evadb/utils/generic_utils.py
  script/test/test.sh
  setup.py
  test/integration_tests/long/test_model_train.py
  test/markers.py
Labels: Feature Request ✨

#1223 fix: native db bugs
  docs/requirements.txt
  evadb/binder/binder_utils.py
  evadb/binder/statement_binder.py
  evadb/catalog/catalog_manager.py
  evadb/executor/create_executor.py
  evadb/storage/native_storage_engine.py
Labels: User Experience, Data Sources

#1229 Fix staging CI setup
  .circleci/config.yml
  test/integration_tests/long/test_similarity.py
  test/util.py
Labels: Bug 🐞

#1228 fix: improve messaging and fix bugs
  evadb/executor/create_executor.py
  evadb/executor/load_csv_executor.py
  evadb/storage/native_storage_engine.py
  test/integration_tests/long/test_similarity.py
Labels: Bug 🐞, User Experience

#1111 add stable diffusion integration
  evadb/functions/dalle.py
  evadb/functions/function_bootstrap_queries.py
  evadb/functions/stable_diffusion.py
  evadb/utils/generic_utils.py
  test/integration_tests/long/functions/test_dalle.py
  test/integration_tests/long/functions/test_selfdiffusion.py
  test/markers.py
  tutorials/16-stable-diffusion.ipynb
Labels: AI Engines

#1115 Add support for Neuralforecast
  data/forecasting/AirPassengersPanel.csv
  docs/source/reference/ai/model-forecasting.rst
  evadb/binder/statement_binder.py
  evadb/executor/create_function_executor.py
  evadb/functions/forecast.py
  evadb/utils/generic_utils.py
  setup.py
  test/integration_tests/long/test_model_forecasting.py
  test/unit_tests/binder/test_statement_binder.py
  tutorials/16-homesale-forecasting.ipynb
Labels: Integrations 🧩, AI Engines
