Repository georgia-tech-db/evadb, pull requests merged in 2023-05, with the labels that each got.

#655 feat: LLM-based remote UDFs -- support for ChatGPT
  eva/eva.yml
  eva/udfs/openai_chat_completion_udf.py
  setup.py
  test/integration_tests/test_openai_chat_completion_udf.py
  test/markers.py
Labels: enhancement, High Priority, feature-llm

#698 docs: improve UDF creation documentation
  docs/_toc.yml
  docs/source/reference/udfs/custom.rst
  docs/source/reference/udfs/hf.rst
  docs/source/reference/udfs/openai.rst
  docs/source/reference/udfs/yolo.rst
  eva/udfs/fastrcnn_object_detector.py
Labels: documentation

#702 fix: stop raising error if category or key missing in config.
  eva/configuration/configuration_manager.py
  test/configuration/test_configuration_manager.py
Labels: bug

#701 bug: modify the catalog reset method
  eva/catalog/catalog_manager.py
  eva/catalog/models/base_model.py
  test/catalog/test_catalog_manager.py
Labels: bug

#704 test: add message to help debug an issue
  test/integration_tests/test_reuse.py
Labels: bug

#706 bug: catalog reset
  eva/catalog/catalog_manager.py
  eva/catalog/models/base_model.py
  eva/catalog/sql_config.py
Labels: bug

#711 docs: Update README.md / typo fix
  README.md
Labels: 🎉 first-time-contributor

#712 fix: image loading
  eva/executor/load_multimedia_executor.py
  eva/storage/abstract_media_storage_engine.py
  test/benchmark_tests/test_benchmark_pytorch.py
  test/integration_tests/test_load_executor.py
  test/util.py
Labels: enhancement

#727 typo: "recogizing" in index.rst
  docs/index.rst
Labels: 🎉 first-time-contributor

#566 feat: object tracking
  eva/binder/binder_utils.py
  eva/binder/statement_binder.py
  eva/executor/apply_and_merge_executor.py
  eva/expression/abstract_expression.py
  eva/optimizer/operators.py
  eva/optimizer/rules/rules.py
  eva/optimizer/rules/rules_base.py
  eva/optimizer/rules/rules_manager.py
  eva/optimizer/statement_to_opr_convertor.py
  eva/parser/types.py
  eva/udfs/abstract/tracker_abstract_udf.py
  eva/udfs/decorators/utils.py
  eva/udfs/trackers/__init__.py
  eva/udfs/trackers/nor_fair.py
  eva/udfs/udf_bootstrap_queries.py
  eva/utils/math_utils.py
  setup.py
  test/integration_tests/test_optimizer_rules.py
  test/integration_tests/test_pytorch.py
  test/integration_tests/test_reuse.py
  test/optimizer/rules/test_rules.py
  test/optimizer/test_statement_to_opr_convertor.py
Labels: Feature Request ✨, High Priority ⚡️

#738 feat: allow users to specify host and port while launching server
  db_api_example.py
  docs/source/overview/installation.rst
  eva/eva.yml
  eva/eva_cmd_client.py
  eva/eva_server.py
  eva/server/interpreter.py
  eva/server/server.py
  eva/version.py
  script/test/package.sh
  test/server/test_server.py
  test/test_eva_cmd_client.py
  test/test_eva_server.py
  tutorials/00-start-eva-server.ipynb
  tutorials/06-loading-structured-data.ipynb
  tutorials/07-object-segmentation-huggingface.ipynb
Labels: Feature Request ✨

#700 doc: similarity search tutorial
  .gitignore
  eva/configuration/bootstrap_environment.py
  eva/executor/load_multimedia_executor.py
  eva/udfs/sift_feature_extractor.py
  eva/udfs/udf_bootstrap_queries.py
  script/formatting/spelling.txt
  setup.py
  tutorials/11-similarity-search-for-motif-mining.ipynb
Labels: Feature Request ✨, Documentation 📗

#774 Improve create mat
  eva/binder/statement_binder.py
  eva/eva.yml
  eva/executor/create_mat_view_executor.py
  eva/parser/create_mat_view_statement.py
  eva/parser/lark_visitor/_create_statements.py
  test/binder/test_statement_binder.py
  test/executor/test_create_mat_executor.py
  test/integration_tests/test_mat_executor.py
  tutorials/01-mnist.ipynb
Labels: Work In Progress 🚧

#784 feat: support relational apis
  .gitignore
  db_api_example.py
  docs/Makefile
  docs/_toc.yml
  docs/requirements.txt
  docs/source/reference/python/api.rst
  docs/source/reference/python/db.rst
  docs/source/reference/python/df.rst
  eva/expression/function_expression.py
  eva/interfaces/__init__.py
  eva/interfaces/relational/__init__.py
  eva/interfaces/relational/db.py
  eva/interfaces/relational/relation.py
  eva/interfaces/relational/utils.py
  eva/parser/lark_visitor/_table_sources.py
  eva/parser/select_statement.py
  eva/parser/statement.py
  eva/parser/table_ref.py
  eva/parser/utils.py
  eva/server/db_api.py
  eva/server/interpreter.py
  eva/third_party/vector_stores/faiss.py
  script/formatting/spelling.txt
  test/interfaces/relational/__init__.py
  test/interfaces/relational/test_relational_api.py
  test/server/test_db_api.py
  test/server/test_interpreter.py
  tutorials/00-start-eva-server.ipynb
Labels: High Priority ⚡️, High Effort 🏋

#789 feat: create table from select query
  eva/binder/statement_binder.py
  eva/executor/create_executor.py
  eva/optimizer/plan_generator.py
  eva/optimizer/rules/rules.py
  eva/optimizer/rules/rules_base.py
  eva/optimizer/rules/rules_manager.py
  eva/optimizer/statement_to_opr_converter.py
  eva/parser/create_statement.py
  eva/parser/eva.lark
  eva/parser/lark_visitor/_create_statements.py
  eva/plan_nodes/create_plan.py
  test/integration_tests/test_create_table_executor.py
  test/optimizer/rules/test_rules.py
Labels: Feature Request ✨
