Repository georgia-tech-db/evadb, pull requests merged in 2023-10, with the labels that each got.

#1233 GitHub Data Source Integration
  .circleci/config.yml
  docs/_toc.yml
  docs/source/reference/databases/github.rst
  evadb/binder/statement_binder_context.py
  evadb/catalog/catalog_manager.py
  evadb/storage/native_storage_engine.py
  evadb/storage/sqlite_storage_engine.py
  evadb/third_party/databases/github/__init__.py
  evadb/third_party/databases/github/github_handler.py
  evadb/third_party/databases/github/requirements.txt
  evadb/third_party/databases/github/table_column_info.py
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/types.py
  evadb/utils/generic_utils.py
  evadb/version.py
  test/integration_tests/long/test_fuzzy_join.py
  test/third_party_tests/test_github_datasource.py
Labels: Integrations 🧩, Data Sources

#1244 feat: create index from projection
  evadb/binder/binder_utils.py
  evadb/binder/create_index_statement_binder.py
  evadb/binder/statement_binder.py
  evadb/binder/tuple_value_expression_binder.py
  evadb/catalog/catalog_manager.py
  evadb/catalog/models/index_catalog.py
  evadb/catalog/models/utils.py
  evadb/catalog/services/index_catalog_service.py
  evadb/executor/create_index_executor.py
  evadb/optimizer/operators.py
  evadb/optimizer/rules/rules.py
  evadb/optimizer/statement_to_opr_converter.py
  evadb/parser/create_index_statement.py
  evadb/parser/lark_visitor/_create_statements.py
  evadb/plan_nodes/create_index_plan.py
  test/integration_tests/long/test_create_index_executor.py
  test/unit_tests/binder/test_statement_binder.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
  test/unit_tests/parser/test_parser.py
Labels: Feature Request ✨, Optimizations

#1245 Documentation on vector stores + vector benchmark
  docs/_toc.yml
  docs/source/reference/vector_stores/chromadb.rst
  docs/source/reference/vector_stores/faiss.rst
  docs/source/reference/vector_stores/index.rst
  docs/source/reference/vector_stores/pgvector.rst
  docs/source/reference/vector_stores/pinecone.rst
  docs/source/reference/vector_stores/qdrant.rst
Labels: Documentation 📗, User Experience

#1246 feat: insertion update index
  docs/source/reference/evaql/insert.rst
  evadb.db
  evadb/executor/create_index_executor.py
  evadb/executor/insert_executor.py
  evadb/parser/create_index_statement.py
  evadb/third_party/vector_stores/faiss.py
  test/integration_tests/long/test_create_index_executor.py
  test/integration_tests/long/test_similarity.py
Labels: Feature Request ✨, User Experience

#1253 Collection of fixes for the staging branch
  docs/source/reference/databases/github.rst
  evadb.db
  test/integration_tests/long/interfaces/relational/test_relational_api.py
  test/integration_tests/long/test_github_datasource.py
Labels: Bug 🐞

#1256 Remove table names from column names for `df()` call
  docs/source/reference/api.rst
  evadb/interfaces/relational/db.py
  evadb/interfaces/relational/relation.py
  test/integration_tests/long/interfaces/relational/test_relational_api.py
Labels: User Experience

#1261 Remove dimensions from `TEXT` and `FLOAT`
  docs/source/reference/evaql/create.rst
  docs/source/shared/postgresql.rst
  evadb/parser/lark_visitor/_create_statements.py
  test/unit_tests/parser/test_parser.py
Labels: Feature Request ✨, User Experience

#1267 Improve the error message when there is a typo in the column name in the query.
  evadb/binder/statement_binder_context.py
  test/integration_tests/short/test_select_executor.py
Labels: User Experience

#1270 fix: Catalog init introduces significant overhead
  evadb/executor/abstract_executor.py
  evadb/executor/apply_and_merge_executor.py
  evadb/executor/executor_utils.py
  evadb/executor/function_scan_executor.py
  evadb/executor/hash_join_executor.py
  evadb/executor/lateral_join_executor.py
  evadb/executor/nested_loop_join_executor.py
  evadb/executor/plan_executor.py
  evadb/executor/predicate_executor.py
  evadb/executor/project_executor.py
  evadb/executor/seq_scan_executor.py
Labels: Bug 🐞

#1273 Update custom-ai-function.rst
  docs/source/reference/ai/custom-ai-function.rst
Labels: Documentation 📗

#1234 Added basic functionalities of REST apis
  apps/rest/README.md
  apps/rest/run_evadb.py
Labels: Feature Request ✨, User Experience

#1285 Update custom-ai-function.rst
  docs/source/reference/ai/custom-ai-function.rst
  test/third_party_tests/test_native_executor.py
Labels: Documentation 📗

#1240 Add stable diffusion integration
  docs/_toc.yml
  docs/source/reference/ai/stablediffusion.rst
  evadb/evadb.yml
  evadb/functions/dalle.py
  evadb/functions/function_bootstrap_queries.py
  evadb/functions/stable_diffusion.py
  evadb/utils/generic_utils.py
  script/test/test.sh
  setup.py
  test/integration_tests/long/functions/test_stablediffusion.py
  test/markers.py
  test/unit_tests/test_dalle.py
  tutorials/18-stable-diffusion.ipynb
Labels: AI Engines

#1296 feat: function_metadata supports boolean and float
  evadb/catalog/models/function_metadata_catalog.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_expressions.py
  test/integration_tests/long/test_function_executor.py
Labels: Feature Request ✨

#1295 feat: add support for show databases
  evadb/catalog/catalog_manager.py
  evadb/executor/show_info_executor.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_show_statements.py
  evadb/parser/show_statement.py
  evadb/parser/types.py
  evadb/plan_nodes/show_info_plan.py
  test/integration_tests/short/test_show_info_executor.py
  test/unit_tests/parser/test_parser_statements.py
Labels: Feature Request ✨

#1293 fix: make the table/function catalog insert operation atomic
  evadb/binder/statement_binder.py
  evadb/catalog/catalog_manager.py
  evadb/catalog/services/column_catalog_service.py
  evadb/catalog/services/function_catalog_service.py
  evadb/catalog/services/function_io_catalog_service.py
  evadb/catalog/services/function_metadata_catalog_service.py
  evadb/catalog/services/table_catalog_service.py
  evadb/catalog/sql_config.py
  test/integration_tests/long/test_create_table_executor.py
  test/unit_tests/catalog/test_catalog_manager.py
Labels: Bug 🐞

#1294 fix: improve testcase
  evadb/configuration/constants.py
  evadb/optimizer/statement_to_opr_converter.py
  evadb/parser/lark_visitor/_expressions.py
  evadb/parser/utils.py
  evadb/readers/document/document_reader.py
  test/integration_tests/long/interfaces/relational/test_relational_api.py
  test/unit_tests/optimizer/test_statement_to_opr_converter.py
Labels: Minor 💅

#1283 Fix current issues with forecasting
  evadb/executor/create_function_executor.py
  evadb/functions/forecast.py
Labels: User Experience

#1289 SnowFlake Integration for EvaDB
  docs/_toc.yml
  docs/source/reference/databases/snowflake.rst
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/snowflake/__init__.py
  evadb/third_party/databases/snowflake/requirements.txt
  evadb/third_party/databases/snowflake/snowflake_handler.py
  test/third_party_tests/test_native_executor.py
  test/unit_tests/storage/test_snowflake_native_storage_engine.py
Labels: Data Sources

#1305 Starting the changes for XGBoost classification integration.
  data/classification/Employee.csv
  docs/source/reference/ai/model-train-xgboost.rst
  evadb/configuration/constants.py
  evadb/executor/create_function_executor.py
  test/integration_tests/long/test_model_train.py
Labels: AI Engines

#1298 Convert nested join in Vector Queries to Pandas Merge.
  evadb/executor/vector_index_scan_executor.py
Labels: Optimizations

#1269 Add Milvus integration for vector create and search
  docs/_toc.yml
  docs/source/reference/vector_databases/milvus.rst
  evadb/catalog/catalog_type.py
  evadb/evadb_config.py
  evadb/executor/executor_utils.py
  evadb/interfaces/relational/db.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_create_statements.py
  evadb/third_party/vector_stores/milvus.py
  evadb/third_party/vector_stores/utils.py
  evadb/utils/generic_utils.py
  script/formatting/spelling.txt
  setup.py
  test/integration_tests/long/test_similarity.py
  test/markers.py
Labels: Integrations 🧩, Data Sources

#1316 Adding colab notebook for XGBoost Regression and Classification
  tutorials/17-home-rental-prediction.ipynb
  tutorials/19-employee-classification-prediction.ipynb
Labels: AI Engines

#1323 Added docs for SET and SHOW CONFIG query
  docs/_toc.yml
  docs/source/reference/evaql/set_config.rst
  docs/source/reference/evaql/show_config.rst
Labels: Documentation 📗, User Experience

#1321 REST API Documentation
  docs/_toc.yml
  docs/source/reference/rest_api.rst
Labels: Documentation 📗, User Experience

#1322 String Helper functions in EvaDB
  evadb/functions/function_bootstrap_queries.py
  evadb/functions/helpers/concat.py
  evadb/functions/helpers/lower.py
  evadb/functions/helpers/upper.py
  test/integration_tests/long/functions/helpers/test_str_helper_functions.py
Labels: User Experience

#1317 Create a roadmap page in documentation to align the focus and priority.
  docs/_toc.yml
  docs/source/overview/roadmap.rst
Labels: Documentation 📗

#1325 Update Readme with more details and fix notebook tests
  README.md
  script/test/test.sh
Labels: User Experience
