Repository georgia-tech-db/evadb, pull requests merged in 2023-11, with the labels that each got.

#1337 CREATE INDEX IF NOT EXISTS is broken.
  evadb/executor/insert_executor.py
  evadb/executor/vector_index_scan_executor.py
  test/integration_tests/long/test_similarity.py
Labels: Bug 🐞

#1033 feat: third party app support in EVADB
  evadb/third_party/databases/interface.py
  evadb/third_party/databases/slack/__init__.py
  evadb/third_party/databases/slack/slack_handler.py
Labels: Integrations 🧩, Data Sources

#1334 logging an error message for invalid files while loading
  evadb/executor/load_multimedia_executor.py
  test/integration_tests/long/test_load_executor.py
Labels: User Experience

#1342 Add train scores for ludwig in the create function handler.
  docs/source/overview/concepts.rst
  docs/source/reference/ai/model-forecasting.rst
  docs/source/reference/databases/github.rst
  evadb/executor/create_function_executor.py
Labels: AI Engines

#1364 Fix python3.8 failing testcases due to type hint
  evadb/catalog/catalog_manager.py
  evadb/catalog/services/job_history_catalog_service.py
Labels: Bug 🐞

#1361 Adding changes for Flaml Sklearn integration
  evadb/configuration/constants.py
  evadb/executor/create_function_executor.py
  evadb/functions/sklearn.py
  evadb/functions/xgboost.py
  evadb/utils/generic_utils.py
  test/integration_tests/long/test_model_train.py
  test/markers.py
Labels: AI Engines

#1368 Migrate ChatGPT function to openai v1.0
  evadb/functions/chatgpt.py
  evadb/functions/dalle.py
  setup.py
  test/integration_tests/long/functions/test_chatgpt.py
  test/unit_tests/test_dalle.py
Labels: AI Engines

#1362 Hackernews search in EVADB
  docs/_toc.yml
  docs/source/reference/databases/hackernews.rst
  evadb/third_party/databases/hackernews/__init__.py
  evadb/third_party/databases/hackernews/hackernews_handler.py
  evadb/third_party/databases/hackernews/table_column_info.py
  evadb/third_party/databases/interface.py
  setup.py
  test/integration_tests/long/test_hackernews_datasource.py
Labels: Integrations 🧩, AI Engines, Data Sources

#1374 Fix the 'DataFrame' object has no attribute 'map' when panda < 2.1.0 is used.
  setup.py
Labels: Bug 🐞

#1360 Add Weaviate integration
  docs/_toc.yml
  docs/source/reference/databases/hackernews.rst
  docs/source/reference/vector_databases/weaviate.rst
  evadb/catalog/catalog_type.py
  evadb/evadb_config.py
  evadb/executor/executor_utils.py
  evadb/interfaces/relational/db.py
  evadb/parser/evadb.lark
  evadb/parser/lark_visitor/_create_statements.py
  evadb/third_party/vector_stores/utils.py
  evadb/third_party/vector_stores/weaviate.py
  evadb/utils/generic_utils.py
  script/formatting/spelling.txt
  setup.py
  test/integration_tests/long/test_similarity.py
  test/markers.py
Labels: Data Sources

#1376 Fix COUNT(*) ERROR for PDF SELECT Queries
  evadb/parser/lark_visitor/_functions.py
  test/data/uadetrac/small-data/pdf_data/fall_2023_orientation_document.pdf
  test/integration_tests/short/test_select_executor.py
Labels: Bug 🐞

#1345 `SHOW CONFIGS` now gets all configs
  .gitignore
  docs/source/reference/evaql/set_config.rst
  docs/source/reference/evaql/show_config.rst
  evadb/catalog/catalog_manager.py
  evadb/evadb_config.py
  evadb/executor/set_executor.py
  evadb/executor/show_info_executor.py
  evadb/parser/lark_visitor/_show_statements.py
  evadb/parser/show_statement.py
  evadb/parser/types.py
  evadb/plan_nodes/show_info_plan.py
  test/integration_tests/short/test_show_info_executor.py
  test/unit_tests/parser/test_parser.py
Labels: User Experience

#1392 Notifying users about incorrect forward headers
  evadb/functions/decorators/utils.py
Labels: User Experience
